name: online_food_ordering_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  flutter_iconly: ^1.0.2
  shimmer: ^3.0.0
  fancy_shimmer_image: ^2.0.3
  dynamic_height_grid_view: ^0.0.4
  card_swiper: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  collection: ^1.19.0
  material_color_utilities: ^0.12.0
  leak_tracker: ^10.0.7
  leak_tracker_flutter_testing: ^3.0.8
  string_scanner: ^1.3.0
  test_api: ^0.7.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    
